# Generated by Django 5.2.1 on 2025-05-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("node_id", models.IntegerField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
            ],
        ),
    ]
